name: Exercise

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # - uses: https://gitlab.com/da_doomer/markdown-slides
      - name:
        run: pip install git+https://gitlab.com/da_doomer/markdown-slides
      - uses: actions/upload-pages-artifact
      - uses: actions/deploy-pages