name: First CI Job

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]
        include:
          - os: macos-14
            python-version: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - id: step1
        run: echo "myvar=42" >> $GITHUB_ENV
      - run: echo "myvar = ${{ steps.step1.outputs.myvar }}"
      - run: echo $myvar
      - run: echo ${{ env.myvar }}
      - run: echo Hello world.
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - if: runner.os == 'Linux'
        run: echo This is Linux
      - run: echo This is ${{ runner.os }}
      # This is to run the tests
      - run: python -m pip install .[test]
      - run: python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploy jobs"